# ReadBridge Web Scraping ETL Pipeline

## Project Overview

This project demonstrates an end-to-end ETL pipeline that extracts book data
from a multi-page website, transforms the raw data into a structured and
analysis-ready format, and loads the processed dataset into a PostgreSQL
database.

The project was developed to demonstrate practical data engineering concepts
including web scraping, data transformation, data quality validation,
environment variable management, relational database integration, and
pipeline development using Python.

## ETL Architecture

Website
   ↓
Python / BeautifulSoup
   ↓
Raw Data
   ↓
Pandas Data Transformation
   ↓
Data Quality Checks
   ↓
SQLAlchemy
   ↓
PostgreSQL

## Extract

Book information was extracted from multiple pages using Python,
Requests, and BeautifulSoup.

The extraction process collects attributes including:

- Book title
- Price
- Rating
- Availability
- Source page
- Extraction timestamp

Pagination logic was implemented to collect records across multiple
web pages rather than processing only a single page.

## Transform

The extracted data was transformed with Pandas before database loading.

Transformation steps included:

- Removing unnecessary characters from price values
- Converting prices to numeric data types
- Converting textual star ratings into numeric ratings
- Standardizing availability values
- Extracting numeric page numbers from pagination text
- Creating an extraction timestamp (`scraped_at`)
- Checking for missing and inconsistent values

These transformations produce a structured dataset suitable for
database storage and downstream analysis.

## Load

The transformed dataset was loaded into PostgreSQL using SQLAlchemy.

Database credentials are managed using environment variables rather
than being hard-coded into the application.

The `.env` file containing database credentials is excluded from
version control using `.gitignore`.

## PostgreSQL Output

The following screenshot shows the transformed dataset successfully
loaded into PostgreSQL:

![PostgreSQL Loaded Data](images/postgresql_loaded_data.png)

## Technology Stack

- Python
- Pandas
- BeautifulSoup
- Requests
- PostgreSQL
- SQLAlchemy
- psycopg2
- python-dotenv
- Jupyter Notebook
- Git & GitHub

## Data Engineering Concepts Demonstrated

This project demonstrates several core data engineering practices:

- ETL pipeline development
- Multi-page web data extraction
- Data cleaning and transformation
- Data type standardization
- Data quality validation
- Relational database loading
- Secure credential management
- Environment variable configuration
- Reproducible project structure
- Version control with Git

In [535]:
import requests                          # HTTP fetching
from bs4 import BeautifulSoup            # HTML parsing
import pandas as pd                      # Tabular data
import sqlite3                           # Local database
import time                              # Polite pauses between requests
import os
from datetime import datetime

print('✅ All libraries imported successfully')

✅ All libraries imported successfully

In [536]:
# ── Always check status before scraping ──────────────────────────────────
def safe_get(url, delay=1):
    """Fetch a URL, return None if it fails, and sleep politely after."""
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()    # Raises exception for 4xx / 5xx codes
        time.sleep(delay)              # Polite pause — never hammer a server
        return response
    except requests.RequestException as e:
        print(f'❌ Request failed: {e}')
        return None

resp = safe_get('https://books.toscrape.com')
if resp:
    print(f'✅ Got {len(resp.text):,} chars')

✅ Got 51,294 chars

In [527]:
with open('books.toscrape.html', 'r', encoding='utf-8') as f:
    html = f.read()

print(f'HTML file loaded: {len(html):,} characters')
soup = BeautifulSoup(html, 'html.parser')
print('BeautifulSoup object created ✅')

HTML file loaded: 51,274 characters
BeautifulSoup object created ✅

In [537]:
resp = safe_get('https://books.toscrape.com/catalogue/page-1.html')
soup = BeautifulSoup(resp.text, 'html.parser')


books_cards = soup.find_all('div', class_='page_inner')
print(f'Found {len(books_cards)} books cards')

# Preview the first card's raw HTML
print('\n--- First card structure ---')
print(books_cards[0].prettify()[:600])

Found 2 books cards

--- First card structure ---
<div class="page_inner">
 <div class="row">
  <div class="col-sm-8 h1">
   <a href="../index.html">
    Books to Scrape
   </a>
   <small>
    We love being scraped!
   </small>
  </div>
 </div>
</div>

In [538]:
books_cards = soup.find_all('article', class_='product_pod')

print("Number of books:", len(books_cards))

Number of books: 20

In [539]:
print(books_cards[0].prettify())

<article class="product_pod">
 <div class="image_container">
  <a href="a-light-in-the-attic_1000/index.html">
   <img alt="A Light in the Attic" class="thumbnail" src="../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
  </a>
 </div>
 <p class="star-rating Three">
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
 </p>
 <h3>
  <a href="a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
   A Light in the ...
  </a>
 </h3>
 <div class="product_price">
  <p class="price_color">
   Â£51.77
  </p>
  <p class="instock availability">
   <i class="icon-ok">
   </i>
   In stock
  </p>
  <form>
   <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
    Add to basket
   </button>
  </form>
 </div>
</article>

In [540]:
print("number of bookcards:", len(books_cards))

number of bookcards: 20

In [541]:
# ── Step 3: Extract data from one card (prototype before looping) ─────────
card = books_cards[0]   # First book

title  = card.find('h3') .a['title']
price  = card.find('p',    class_='price_color').get_text(strip=True)
availability = card.find('p', class_='instock availability').get_text(strip=True)
rating   = book.find('p', class_='star-rating')['class'][1]
page_number = soup.find('li', class_='current').get_text(strip=True)
scraped_at   = scraped_at = datetime.now()

print(f'Title    : {title}')
print(f'Price  : {price}')
print(f'Rating : {rating}')
print(f'Availability   : {availability}')
print(f'Page Number     : {page_number}')
print(f'Scraped at   : {scraped_at}')

Title    : A Light in the Attic
Price  : Â£51.77
Rating : Three
Availability   : In stock
Page Number     : Page 1 of 50
Scraped at   : 2026-10-02 14:37:15.489809

In [542]:
# ── Step 4: Loop over ALL book cards ────────────────────────────────────────
data = []

for card in books_cards:
    title    = card.find('h3') .a['title']
    price  = card.find('p',    class_='price_color').get_text(strip=True)
    availability = card.find('p', class_='instock availability').get_text(strip=True)
    rating   = book.find('p', class_='star-rating')['class'][1]
    page_number = soup.find('li', class_='current').get_text(strip=True)
    scraped_at   = scraped_at = datetime.now()

    data.append({
        'title'   : title,
        'price' : price,
        'rating': rating,
        'availability'  : availability,
        'page_number': page_number,
        'scraped_at'  : scraped_at   
    })

df = pd.DataFrame(data)
print(f'Scraped {len(df)} book cards')
df.head()

Scraped 20 book cards

,title,price,rating,availability,page_number,scraped_at
0,A Light in the Attic,Â£51.77,Three,In stock,Page 1 of 50,2026-10-02 14:37:18.218155
1,Tipping the Velvet,Â£53.74,Three,In stock,Page 1 of 50,2026-10-02 14:37:18.219569
2,Soumission,Â£50.10,Three,In stock,Page 1 of 50,2026-10-02 14:37:18.220559
3,Sharp Objects,Â£47.82,Three,In stock,Page 1 of 50,2026-10-02 14:37:18.222218
4,Sapiens: A Brief History of Humankind,Â£54.23,Three,In stock,Page 1 of 50,2026-10-02 14:37:18.224046

In [543]:
# ── Full pagination loop — 10 pages ────────────────────────────────────────
BASE_URL  = 'https://books.toscrape.com/catalogue/page-{}.html'
rating_score = {'One' : 1,
                'Two' : 2,
                'Three' : 3,
                'Four' : 4,
                'Five' : 5


}


all_books = []

for page_num in range(1, 11):      # Pages 1, 2, 3.....
    print(f'  📖 Fetching page {page_num}...')

    resp = safe_get(BASE_URL.format(page_num), delay=1)
    if resp is None:
        print(f'  ⚠️  Skipping page {page_num} — request failed')
        continue

    soup = BeautifulSoup(resp.text, 'html.parser')

    for book in soup.find_all('article', class_='product_pod'):
        title    = book.find('h3') .a['title']
        price  = book.find('p',    class_='price_color').get_text(strip=True)
        availability = book.find('p', class_='instock availability').get_text(strip=True)
        rating   = book.find('p', class_='star-rating')['class'][1]
        page_number = soup.find('li', class_='current').get_text(strip=True)
        scraped_at   = scraped_at = datetime.now()

        all_books.append({
            'title'   : title,
            'price' : price,
            'rating': rating,
            'availability'  : availability,
            'page_number': page_number,
            'scraped_at'  : scraped_at  
        })

books_df = pd.DataFrame(all_books)
print(f'\n✅ Scraped {len(books_df)} books across 10 pages')
books_df.head(25)

  📖 Fetching page 1...
  📖 Fetching page 2...
  📖 Fetching page 3...
  📖 Fetching page 4...
  📖 Fetching page 5...
  📖 Fetching page 6...
  📖 Fetching page 7...
  📖 Fetching page 8...
  📖 Fetching page 9...
  📖 Fetching page 10...

✅ Scraped 200 books across 10 pages

,title,price,rating,availability,page_number,scraped_at
0,A Light in the Attic,Â£51.77,Three,In stock,Page 1 of 50,2026-10-02 14:37:26.016604
1,Tipping the Velvet,Â£53.74,One,In stock,Page 1 of 50,2026-10-02 14:37:26.016967
2,Soumission,Â£50.10,One,In stock,Page 1 of 50,2026-10-02 14:37:26.017312
3,Sharp Objects,Â£47.82,Four,In stock,Page 1 of 50,2026-10-02 14:37:26.017707
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,Page 1 of 50,2026-10-02 14:37:26.018058
5,The Requiem Red,Â£22.65,One,In stock,Page 1 of 50,2026-10-02 14:37:26.018403
6,The Dirty Little Secrets of Getting Your Dream...,Â£33.34,Four,In stock,Page 1 of 50,2026-10-02 14:37:26.018741
7,The Coming Woman: A Novel Based on the Life of...,Â£17.93,Three,In stock,Page 1 of 50,2026-10-02 14:37:26.019063
8,The Boys in the Boat: Nine Americans and Their...,Â£22.60,Four,In stock,Page 1 of 50,2026-10-02 14:37:26.019408
9,The Black Maria,Â£52.15,One,In stock,Page 1 of 50,2026-10-02 14:37:26.019732
10,"Starving Hearts (Triangular Trade Trilogy, #1)",Â£13.99,Two,In stock,Page 1 of 50,2026-10-02 14:37:26.020055
11,Shakespeare's Sonnets,Â£20.66,Four,In stock,Page 1 of 50,2026-10-02 14:37:26.020381
12,Set Me Free,Â£17.46,Five,In stock,Page 1 of 50,2026-10-02 14:37:26.020704
13,Scott Pilgrim's Precious Little Life (Scott Pi...,Â£52.29,Five,In stock,Page 1 of 50,2026-10-02 14:37:26.021029
14,Rip it Up and Start Again,Â£35.02,Five,In stock,Page 1 of 50,2026-10-02 14:37:26.021354
15,Our Band Could Be Your Life: Scenes from the A...,Â£57.25,Three,In stock,Page 1 of 50,2026-10-02 14:37:26.021717
16,Olio,Â£23.88,One,In stock,Page 1 of 50,2026-10-02 14:37:26.022187
17,Mesaerion: The Best Science Fiction Stories 18...,Â£37.59,One,In stock,Page 1 of 50,2026-10-02 14:37:26.022555
18,Libertarianism for Beginners,Â£51.33,Two,In stock,Page 1 of 50,2026-10-02 14:37:26.022891
19,It's Only the Himalayas,Â£45.17,Two,In stock,Page 1 of 50,2026-10-02 14:37:26.023225
20,In Her Wake,Â£12.84,One,In stock,Page 2 of 50,2026-10-02 14:37:27.706670
21,How Music Works,Â£37.32,Two,In stock,Page 2 of 50,2026-10-02 14:37:27.707382
22,Foolproof Preserving: A Guide to Small Batch J...,Â£30.52,Three,In stock,Page 2 of 50,2026-10-02 14:37:27.708138
23,Chase Me (Paris Nights #2),Â£25.27,Five,In stock,Page 2 of 50,2026-10-02 14:37:27.708649
24,Black Dust,Â£34.53,Five,In stock,Page 2 of 50,2026-10-02 14:37:27.709117

In [544]:
# ── Save and inspect ──────────────────────────────────────────────────────
books_df.to_csv('books_10pages.csv', index=False)
print('Saved to books_10pages.csv')

# Distribution by rating
print('\nBooks by rating:')
print(books_df['rating'].value_counts())

# Price column is a string — quick cleanup
books_df['price_num'] = books_df['price'].str.replace('Â£', '', regex=False).str.replace('£', '', regex=False).astype(float)
print(f'\nPrice range: £{books_df["price_num"].min()} – £{books_df["price_num"].max()}')
print(f'Average price: £{books_df["price_num"].mean():.2f}')

Saved to books_10pages.csv

Books by rating:
rating
One      49
Two      41
Four     38
Five     37
Three    35
Name: count, dtype: int64

Price range: £10.16 – £59.64
Average price: £34.80

In [546]:
books_df ['page_number'].value_counts()

page_number
Page 1 of 50     20
Page 2 of 50     20
Page 3 of 50     20
Page 4 of 50     20
Page 5 of 50     20
Page 6 of 50     20
Page 7 of 50     20
Page 8 of 50     20
Page 9 of 50     20
Page 10 of 50    20
Name: count, dtype: int64

In [547]:
books_df

,title,price,rating,availability,page_number,scraped_at,price_num
0,A Light in the Attic,Â£51.77,Three,In stock,Page 1 of 50,2026-10-02 14:37:26.016604,51.77
1,Tipping the Velvet,Â£53.74,One,In stock,Page 1 of 50,2026-10-02 14:37:26.016967,53.74
2,Soumission,Â£50.10,One,In stock,Page 1 of 50,2026-10-02 14:37:26.017312,50.10
3,Sharp Objects,Â£47.82,Four,In stock,Page 1 of 50,2026-10-02 14:37:26.017707,47.82
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,Page 1 of 50,2026-10-02 14:37:26.018058,54.23
...,...,...,...,...,...,...,...
195,Eureka Trivia 6.0,Â£54.59,Four,In stock,Page 10 of 50,2026-10-02 14:37:41.253168,54.59
196,Drive: The Surprising Truth About What Motivat...,Â£34.95,Four,In stock,Page 10 of 50,2026-10-02 14:37:41.253712,34.95
197,Done Rubbed Out (Reightman & Bailey #1),Â£37.72,Five,In stock,Page 10 of 50,2026-10-02 14:37:41.254262,37.72
198,Doing It Over (Most Likely To #1),Â£35.61,Three,In stock,Page 10 of 50,2026-10-02 14:37:41.254770,35.61
199,Deliciously Ella Every Day: Quick and Easy Rec...,Â£42.16,Three,In stock,Page 10 of 50,2026-10-02 14:37:41.255267,42.16

In [548]:
print("Shape:", books_df.dtypes)

Shape: title                      str
price                      str
rating                     str
availability               str
page_number                str
scraped_at      datetime64[us]
price_num              float64
dtype: object

In [563]:
###Data cleaning ( Clean price and convert to numeric)

clean_books_df = books_df.copy()
clean_books_df['price'] = (
    clean_books_df['price']
    .str.replace('Â£', '', regex=False)
    .str.replace('£', '', regex=False)
    .str.strip()
)

In [564]:
# 2. Clean title
clean_books_df['title'] = (
    clean_books_df['title']
    .str.strip()
)

In [565]:
# 3. Clean availability
clean_books_df['availability'] = (
    clean_books_df['availability']
    .str.strip()
)

In [566]:
# 4. Extract page number as an integer
clean_books_df['page_number'] = (
    clean_books_df['page_number']
    .str.extract(r'Page (\d+)')[0]
    .astype(int)
)

In [567]:
# 5. Convert scraped_at to datetime
# Convert scraped_at to datetime
clean_books_df['scraped_at'] = pd.to_datetime(
    clean_books_df['scraped_at'],
    errors='coerce'
)

# Keep only date, hour, minute and second
clean_books_df['scraped_at'] = clean_books_df['scraped_at'].dt.strftime(
    "%Y-%m-%d %H:%M:%S"
)

In [568]:

# 6. Remove duplicate rows
clean_books_df = clean_books_df.drop_duplicates()

In [569]:
# 7. Reset index
clean_books_df = clean_books_df.reset_index(drop=True)

In [570]:
#8. Convert rating to integer
rating_map = {
    'One': 1,
    'Two': 2,
    'Three': 3,
    'Four': 4,
    'Five': 5
}

clean_books_df['rating'] = (
    clean_books_df['rating']
    .map(rating_map)
)

In [571]:
clean_books_df.head(25)

,title,price,rating,availability,page_number,scraped_at,price_num
0,A Light in the Attic,51.77,3,In stock,1,2026-10-02 14:37:26,51.77
1,Tipping the Velvet,53.74,1,In stock,1,2026-10-02 14:37:26,53.74
2,Soumission,50.10,1,In stock,1,2026-10-02 14:37:26,50.10
3,Sharp Objects,47.82,4,In stock,1,2026-10-02 14:37:26,47.82
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,1,2026-10-02 14:37:26,54.23
5,The Requiem Red,22.65,1,In stock,1,2026-10-02 14:37:26,22.65
6,The Dirty Little Secrets of Getting Your Dream...,33.34,4,In stock,1,2026-10-02 14:37:26,33.34
7,The Coming Woman: A Novel Based on the Life of...,17.93,3,In stock,1,2026-10-02 14:37:26,17.93
8,The Boys in the Boat: Nine Americans and Their...,22.60,4,In stock,1,2026-10-02 14:37:26,22.60
9,The Black Maria,52.15,1,In stock,1,2026-10-02 14:37:26,52.15
10,"Starving Hearts (Triangular Trade Trilogy, #1)",13.99,2,In stock,1,2026-10-02 14:37:26,13.99
11,Shakespeare's Sonnets,20.66,4,In stock,1,2026-10-02 14:37:26,20.66
12,Set Me Free,17.46,5,In stock,1,2026-10-02 14:37:26,17.46
13,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,5,In stock,1,2026-10-02 14:37:26,52.29
14,Rip it Up and Start Again,35.02,5,In stock,1,2026-10-02 14:37:26,35.02
15,Our Band Could Be Your Life: Scenes from the A...,57.25,3,In stock,1,2026-10-02 14:37:26,57.25
16,Olio,23.88,1,In stock,1,2026-10-02 14:37:26,23.88
17,Mesaerion: The Best Science Fiction Stories 18...,37.59,1,In stock,1,2026-10-02 14:37:26,37.59
18,Libertarianism for Beginners,51.33,2,In stock,1,2026-10-02 14:37:26,51.33
19,It's Only the Himalayas,45.17,2,In stock,1,2026-10-02 14:37:26,45.17
20,In Her Wake,12.84,1,In stock,2,2026-10-02 14:37:27,12.84
21,How Music Works,37.32,2,In stock,2,2026-10-02 14:37:27,37.32
22,Foolproof Preserving: A Guide to Small Batch J...,30.52,3,In stock,2,2026-10-02 14:37:27,30.52
23,Chase Me (Paris Nights #2),25.27,5,In stock,2,2026-10-02 14:37:27,25.27
24,Black Dust,34.53,5,In stock,2,2026-10-02 14:37:27,34.53

In [572]:
print("Shape:", clean_books_df.shape)

print("\nMissing values:")
print(clean_books_df.isnull().sum())

print("\nDuplicate rows:")
print(clean_books_df.duplicated().sum())

print("\nData types:")
print(clean_books_df.dtypes)

print("\nBooks per page:")
print(clean_books_df['page_number'].value_counts().sort_index())

Shape: (200, 7)

Missing values:
title           0
price           0
rating          0
availability    0
page_number     0
scraped_at      0
price_num       0
dtype: int64

Duplicate rows:
0

Data types:
title               str
price               str
rating            int64
availability        str
page_number       int64
scraped_at          str
price_num       float64
dtype: object

Books per page:
page_number
1     20
2     20
3     20
4     20
5     20
6     20
7     20
8     20
9     20
10    20
Name: count, dtype: int64

In [573]:

## Loading to POSTGRES

import os
from sqlalchemy import create_engine
from urllib.parse import quote_plus
from dotenv import load_dotenv

# Explicitly loading the .env file from the project folder
load_dotenv(".env")

password = os.getenv("POSTGRES_PASSWORD")

# Safe test - 
print("Password found:", password is not None)

if password is None:
    raise ValueError("POSTGRES_PASSWORD was not found in the .env file")

encoded_pwd = quote_plus(password)

engine = create_engine(
    f"postgresql+psycopg2://postgres:{encoded_pwd}@localhost:5432/Readbridge_ng_db"
)

try:
    with engine.connect() as connection:
        print("Database connection established successfully!")

except Exception as e:
    print("Connection failed:", e)

Password found: True
Database connection established successfully!

In [577]:
clean_books_df.to_sql("Readbridge_ng_scraping", engine, if_exists="append", index=False)

200

In [574]:
df.to_sql(
    "Readbridge_ng_scraping",
    engine,
    if_exists="replace",
    index=False
)

print("Cleaned data replaced successfully!")

Cleaned data replaced successfully!